import React from 'react';
import { motion } from 'framer-motion';
import { Shield, Lock, Eye, Server, FileText, Globe, Key, Database, AlertCircle, RefreshCw, Mail } from 'lucide-react';
import usePageTitle from '../hooks/usePageTitle';


import usePageContent from '../hooks/usePageContent';

const PrivacyPolicy = () => {
    usePageTitle('Privacy Policy');
    const { page } = usePageContent('privacy');
    const header = page?.content?.header || {};
    const content = page?.content?.content || {};

    return (
        <div className="bg-white dark:bg-primary min-h-screen pt-20 transition-colors duration-300">
            <section className="py-20 text-center bg-gray-50 dark:bg-gray-900/50 transition-colors duration-300">
                <h1 className="text-4xl md:text-6xl font-bold text-gray-900 dark:text-white mb-6">
                    {header.title ? <span dangerouslySetInnerHTML={{ __html: header.title }} /> : (<span>Privacy <span className="text-secondary">Policy</span></span>)}
                </h1>
                <p className="text-xl text-gray-600 dark:text-gray-400 max-w-3xl mx-auto px-4">
                    {header.description || "We value your privacy and are committed to protecting your personal data."}
                </p>
                <p className="text-sm text-gray-500 dark:text-gray-500 mt-4">Last Updated: December 20, 2025</p>
            </section>

            <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
                {content.body ? (
                    <motion.div 
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="prose prose-lg prose-gray dark:prose-invert max-w-none"
                        dangerouslySetInnerHTML={{ __html: content.body }}
                    />
                ) : (
                    <motion.div 
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="prose prose-lg prose-gray dark:prose-invert max-w-none"
                    >
                    <div className="bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-2xl p-8 mb-12 shadow-sm dark:shadow-none transition-colors">
                        <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                            Welcome to Safe360. We respect your privacy and want to protect your personal information. This Privacy Policy serves to explain how we collect, use, disclose, and safeguard your information when you visit our website safe360.com and use our training platforms, including our VR/AR applications, mobile apps, and Learning Management System (LMS). Please read this privacy policy carefully. If you do not agree with the terms of this privacy policy, please do not access the site.
                        </p>
                        <p className="text-gray-600 dark:text-gray-300 leading-relaxed mt-4">
                            Safe360 ("us", "we", or "our") operates the website and the Safe360 mobile application (the "Service"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
                        </p>
                    </div>

                    <div className="space-y-16">
                        {/* Section 1: Definitions */}
                        <section>
                            <div className="flex items-center space-x-3 mb-6">
                                <FileText className="w-8 h-8 text-secondary" />
                                <h2 className="text-3xl font-bold text-gray-900 dark:text-white m-0">1. Definitions</h2>
                            </div>
                            <div className="text-gray-600 dark:text-gray-400 space-y-4 pl-4 border-l-2 border-gray-200 dark:border-white/10">
                                <p><strong>Service:</strong> Service is the safe360.com website and the Safe360 mobile application operated by Safe360.</p>
                                <p><strong>Personal Data:</strong> Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                                <p><strong>Usage Data:</strong> Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
                                <p><strong>Cookies:</strong> Cookies are small pieces of data stored on your device (computer or mobile device).</p>
                                <p><strong>Data Controller:</strong> Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed.</p>
                                <p><strong>Data Processors (or Service Providers):</strong> Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller.</p>
                                <p><strong>Data Subject (or User):</strong> Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p>
                            </div>
                        </section>

                        {/* Section 2: Information Collection */}
                        <section>
                            <div className="flex items-center space-x-3 mb-6">
                                <Database className="w-8 h-8 text-secondary" />
                                <h2 className="text-3xl font-bold text-gray-900 dark:text-white m-0">2. Information Collection and Use</h2>
                            </div>
                            <p className="text-gray-600 dark:text-gray-400 mb-6">
                                We collect several different types of information for various purposes to provide and improve our Service to you.
                            </p>
                            
                            <h3 className="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Types of Data Collected</h3>
                            
                            <div className="bg-gray-50 dark:bg-white/5 rounded-xl p-6 mb-6 border border-gray-200 dark:border-white/10 transition-colors">
                                <h4 className="text-lg font-bold text-secondary mb-2">Personal Data</h4>
                                <p className="text-gray-600 dark:text-gray-400 mb-4">
                                    While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
                                </p>
                                <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-1">
                                    <li>Email address</li>
                                    <li>First name and last name</li>
                                    <li>Phone number</li>
                                    <li>Address, State, Province, ZIP/Postal code, City</li>
                                    <li>Cookies and Usage Data</li>
                                </ul>
                            </div>

                            <div className="bg-gray-50 dark:bg-white/5 rounded-xl p-6 mb-6 border border-gray-200 dark:border-white/10 transition-colors">
                                <h4 className="text-lg font-bold text-secondary mb-2">Usage Data</h4>
                                <p className="text-gray-600 dark:text-gray-400 mb-4">
                                    We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").
                                </p>
                                <p className="text-gray-600 dark:text-gray-400 mb-4">
                                    This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                                </p>
                                <p className="text-gray-600 dark:text-gray-400">
                                    When you access the Service by or through a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
                                </p>
                            </div>

                            <div className="bg-gray-50 dark:bg-white/5 rounded-xl p-6 border border-gray-200 dark:border-white/10 transition-colors">
                                <h4 className="text-lg font-bold text-secondary mb-2">Tracking & Cookies Data</h4>
                                <p className="text-gray-600 dark:text-gray-400 mb-4">
                                    We use cookies and similar tracking technologies to track the activity on our Service and hold certain information. Cookies are files with small amount of data which may include an anonymous unique identifier.
                                </p>
                                <p className="text-gray-600 dark:text-gray-400">
                                    You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                                </p>
                            </div>
                        </section>

                        {/* Section 3: Use of Data */}
                        <section>
                            <div className="flex items-center space-x-3 mb-6">
                                <Server className="w-8 h-8 text-secondary" />
                                <h2 className="text-3xl font-bold text-gray-900 dark:text-white m-0">3. Use of Data</h2>
                            </div>
                            <p className="text-gray-600 dark:text-gray-400 mb-4">Safe360 uses the collected data for various purposes:</p>
                            <ul className="text-gray-600 dark:text-gray-400 space-y-3 pl-4 border-l-2 border-gray-200 dark:border-white/10">
                                <li className="pl-2"><strong>To provide and maintain the Service:</strong> Ensuring our platform is accessible and functional.</li>
                                <li className="pl-2"><strong>To notify you about changes:</strong> Keeping you updated on new features or maintenance.</li>
                                <li className="pl-2"><strong>To allow interactive features:</strong> Enabling VR simulations and real-time assessments.</li>
                                <li className="pl-2"><strong>To provide customer care and support:</strong> Troubleshooting issues effectively.</li>
                                <li className="pl-2"><strong>To provide analysis:</strong> Gathering valuable information so that we can improve the Service.</li>
                                <li className="pl-2"><strong>To monitor usage:</strong> Tracking patterns to optimize performance.</li>
                                <li className="pl-2"><strong>To detect, prevent and address technical issues:</strong> Ensuring security and stability.</li>
                            </ul>
                        </section>

                        {/* Section 4: Legal Basis (GDPR) */}
                        <section>
                            <div className="flex items-center space-x-3 mb-6">
                                <ScaleIcon className="w-8 h-8 text-secondary" />
                                <h2 className="text-3xl font-bold text-gray-900 dark:text-white m-0">4. Legal Basis for Processing Personal Data Under GDPR</h2>
                            </div>
                            <p className="text-gray-600 dark:text-gray-400 mb-4">
                                If you are from the European Economic Area (EEA), Safe360's legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
                            </p>
                            <p className="text-gray-600 dark:text-gray-400 mb-2">Safe360 may process your Personal Data because:</p>
                            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-2">
                                <li>We need to perform a contract with you.</li>
                                <li>You have given us permission to do so.</li>
                                <li>The processing is in our legitimate interests and it's not overridden by your rights.</li>
                                <li>For payment processing purposes.</li>
                                <li>To comply with the law.</li>
                            </ul>
                        </section>

                        {/* Section 5: Retention */}
                        <section>
                            <div className="flex items-center space-x-3 mb-6">
                                <RefreshCw className="w-8 h-8 text-secondary" />
                                <h2 className="text-3xl font-bold text-gray-900 dark:text-white m-0">5. Retention of Data</h2>
                            </div>
                            <p className="text-gray-600 dark:text-gray-400">
                                Safe360 will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                                <br/><br/>
                                Safe360 will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                            </p>
                        </section>

                        {/* Section 6: Transfer */}
                        <section>
                            <div className="flex items-center space-x-3 mb-6">
                                <Globe className="w-8 h-8 text-secondary" />
                                <h2 className="text-3xl font-bold text-gray-900 dark:text-white m-0">6. Transfer of Data</h2>
                            </div>
                            <p className="text-gray-600 dark:text-gray-400">
                                Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
                                <br/><br/>
                                If you are located outside United Kingdom or Nepal and choose to provide information to us, please note that we transfer the data, including Personal Data, to these locations and process it there.
                                <br/><br/>
                                Safe360 will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
                            </p>
                        </section>

                        {/* Section 7: Disclosure */}
                        <section>
                            <div className="flex items-center space-x-3 mb-6">
                                <Eye className="w-8 h-8 text-secondary" />
                                <h2 className="text-3xl font-bold text-gray-900 dark:text-white m-0">7. Disclosure of Data</h2>
                            </div>
                            <div className="space-y-6">
                                <div>
                                    <h4 className="text-xl font-bold text-gray-900 dark:text-white mb-2">Business Transaction</h4>
                                    <p className="text-gray-600 dark:text-gray-400">If Safe360 is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
                                </div>
                                <div>
                                    <h4 className="text-xl font-bold text-gray-900 dark:text-white mb-2">Disclosure for Law Enforcement</h4>
                                    <p className="text-gray-600 dark:text-gray-400">Under certain circumstances, Safe360 may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
                                </div>
                                <div>
                                    <h4 className="text-xl font-bold text-gray-900 dark:text-white mb-2">Legal Requirements</h4>
                                    <p className="text-gray-600 dark:text-gray-400">Safe360 may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
                                    <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 mt-2">
                                        <li>To comply with a legal obligation</li>
                                        <li>To protect and defend the rights or property of Safe360</li>
                                        <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                                        <li>To protect the personal safety of users of the Service or the public</li>
                                        <li>To protect against legal liability</li>
                                    </ul>
                                </div>
                            </div>
                        </section>

                        {/* Section 8: Security */}
                        <section>
                            <div className="flex items-center space-x-3 mb-6">
                                <Lock className="w-8 h-8 text-secondary" />
                                <h2 className="text-3xl font-bold text-gray-900 dark:text-white m-0">8. Security of Data</h2>
                            </div>
                            <p className="text-gray-600 dark:text-gray-400">
                                The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security. We utilize industry-standard encryption protocols (SSL/TLS) and secure server infrastructure to safeguard your information.
                            </p>
                        </section>

                        {/* Section 9: Rights */}
                        <section>
                            <div className="flex items-center space-x-3 mb-6">
                                <Shield className="w-8 h-8 text-secondary" />
                                <h2 className="text-3xl font-bold text-gray-900 dark:text-white m-0">9. Your Data Protection Rights Under GDPR</h2>
                            </div>
                            <p className="text-gray-600 dark:text-gray-400 mb-6">
                                If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Safe360 aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
                            </p>
                            <div className="grid md:grid-cols-2 gap-6">
                                <div className="bg-gray-50 dark:bg-white/5 p-6 rounded-xl border border-gray-200 dark:border-white/10 transition-colors">
                                    <h4 className="font-bold text-secondary mb-2">Right to Access</h4>
                                    <p className="text-sm text-gray-600 dark:text-gray-400">You have the right to access, update or to delete the information we have on you.</p>
                                </div>
                                <div className="bg-gray-50 dark:bg-white/5 p-6 rounded-xl border border-gray-200 dark:border-white/10 transition-colors">
                                    <h4 className="font-bold text-secondary mb-2">Right of Rectification</h4>
                                    <p className="text-sm text-gray-600 dark:text-gray-400">You have the right to have your information rectified if that information is inaccurate or incomplete.</p>
                                </div>
                                <div className="bg-gray-50 dark:bg-white/5 p-6 rounded-xl border border-gray-200 dark:border-white/10 transition-colors">
                                    <h4 className="font-bold text-secondary mb-2">Right to Object</h4>
                                    <p className="text-sm text-gray-600 dark:text-gray-400">You have the right to object to our processing of your Personal Data.</p>
                                </div>
                                <div className="bg-gray-50 dark:bg-white/5 p-6 rounded-xl border border-gray-200 dark:border-white/10 transition-colors">
                                    <h4 className="font-bold text-secondary mb-2">Right of Restriction</h4>
                                    <p className="text-sm text-gray-600 dark:text-gray-400">You have the right to request that we restrict the processing of your personal information.</p>
                                </div>
                            </div>
                        </section>

                        {/* Section 10: Service Providers */}
                        <section>
                            <div className="flex items-center space-x-3 mb-6">
                                <Key className="w-8 h-8 text-secondary" />
                                <h2 className="text-3xl font-bold text-gray-900 dark:text-white m-0">10. Service Providers</h2>
                            </div>
                            <p className="text-gray-600 dark:text-gray-400 mb-4">
                                We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
                            </p>
                            <p className="text-gray-600 dark:text-gray-400">
                                These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                            </p>
                            
                            <h4 className="text-xl font-bold text-gray-900 dark:text-white mt-6 mb-2">Analytics</h4>
                            <p className="text-gray-600 dark:text-gray-400">
                                We may use third-party Service Providers to monitor and analyze the use of our Service.
                            </p>
                            <ul className="list-disc pl-6 text-gray-600 dark:text-gray-400 mt-2">
                                <li><strong>Google Analytics:</strong> Google Analytics is a web analytics service offered by Google that tracks and reports website traffic.</li>
                            </ul>
                        </section>

                        {/* Contact */}
                        <section className="pt-16 border-t border-gray-200 dark:border-white/10">
                            <div className="flex items-center space-x-3 mb-6">
                                <Mail className="w-8 h-8 text-secondary" />
                                <h2 className="text-3xl font-bold text-gray-900 dark:text-white m-0">Contact Us</h2>
                            </div>
                            <p className="text-gray-600 dark:text-gray-400 mb-6">
                                If you have any questions about this Privacy Policy, please contact us:
                            </p>
                            <div className="grid md:grid-cols-2 gap-8 text-gray-600 dark:text-gray-300">
                                <div>
                                    <p className="font-bold text-gray-900 dark:text-white mb-1">By Email:</p>
                                    <p className="text-secondary">privacy@safe360.com</p>
                                </div>
                                <div>
                                    <p className="font-bold text-gray-900 dark:text-white mb-1">By Mail:</p>
                                    <p>Safe360 HQ, 123 Tech Avenue,<br/>London, EC1A 1BB, United Kingdom</p>
                                </div>
                            </div>
                        </section>
                    </div>
                    {/* Default hardcoded content ends here */}
                    </motion.div>
                )}
            </div>
        </div>
    );
};

// Icon component for Legal Basis section since we missed importing it
const ScaleIcon = (props) => (
    <svg 
        xmlns="http://www.w3.org/2000/svg" 
        width="24" 
        height="24" 
        viewBox="0 0 24 24" 
        fill="none" 
        stroke="currentColor" 
        strokeWidth="2" 
        strokeLinecap="round" 
        strokeLinejoin="round" 
        {...props}
    >
        <path d="m16 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"/>
        <path d="m2 16 3-8 3 8c-.87.65-1.92 1-3 1s-2.13-.35-3-1Z"/>
        <path d="M7 21h10"/>
        <path d="M12 3v18"/>
        <path d="M3 7h2c2 0 5-1 7-2 2 1 5 2 7 2h2"/>
    </svg>
);

export default PrivacyPolicy;
