const express = require('express');
const router = express.Router();
const { protect } = require('../middleware/auth');
const Media = require('../models/Media');
const { createUploader } = require('../middleware/upload');
const path = require('path');
const fs = require('fs');

const upload = createUploader('media');


router.post('/upload', protect, upload.single('file'), async (req, res) => {
    try {
        if (!req.file) {
            return res.status(400).json({ message: 'No file uploaded' });
        }
        const file = req.file;

        const stats = fs.statSync(file.path);
        // Fix: Use the actual file path generated by middleware (date-based), enabling web access
        // Replace backslashes for Windows compatibility
        const imageUrl = `/${file.path.replace(/\\/g, '/')}`;

        const media = new Media({
            filename: file.filename,
            url: imageUrl,
            title: file.originalname,
            altText: file.originalname.split('.')[0], // Default alt text
            size: stats.size,
            mimetype: file.mimetype,
            uploadedBy: req.user // Fix: req.user is likely the ID string from auth middleware
        });

        const createdMedia = await media.save();
        res.status(201).json(createdMedia);
    } catch (error) {
        console.error('Media upload error:', error);
        res.status(500).json({ message: 'Server Error' });
    }
});

// @route GET /api/media
// @desc Get all media files
router.get('/', protect, async (req, res) => {
    try {
        console.log('GET /api/media hit');
        const { page = 1, limit = 20, search } = req.query;
        const query = {};
        
        if (search) {
            query.$or = [
                { title: { $regex: search, $options: 'i' } },
                { altText: { $regex: search, $options: 'i' } },
                { filename: { $regex: search, $options: 'i' } }
            ];
        }

        const count = await Media.countDocuments(query);
        const media = await Media.find(query)
            .sort({ createdAt: -1 })
            .limit(limit * 1)
            .skip((page - 1) * limit)
            .populate('uploadedBy', 'name');

        res.json({
            media,
            totalPages: Math.ceil(count / limit),
            currentPage: Number(page)
        });
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

// @route PUT /api/media/:id
// @desc Update media details
router.put('/:id', protect, async (req, res) => {
    try {
        const { title, altText, caption } = req.body;
        const media = await Media.findById(req.params.id);

        if (!media) {
            return res.status(404).json({ message: 'Media not found' });
        }

        media.title = title !== undefined ? title : media.title;
        media.altText = altText !== undefined ? altText : media.altText;
        media.caption = caption !== undefined ? caption : media.caption;

        const updatedMedia = await media.save();
        res.json(updatedMedia);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
});

// @route DELETE /api/media/:id
// @desc Delete media file
router.delete('/:id', protect, async (req, res) => {
    try {
        const media = await Media.findById(req.params.id);

        if (!media) {
            return res.status(404).json({ message: 'Media not found' });
        }

        // Try to delete file from filesystem
        // Assuming path stored in DB is relative to public folder e.g. /uploads/media/file.jpg
        const relativePath = media.url;
        // Construct absolute path. Assuming server/routes/media.js, we need to go up to client/public
        const absolutePath = path.join(__dirname, '../../client/public', relativePath);
        
        try {
             if (fs.existsSync(absolutePath)) {
                 fs.unlinkSync(absolutePath);
             }
        } catch (err) {
            console.error('Failed to delete file on disk:', err);
        }

        await media.deleteOne();
        res.json({ message: 'Media removed' });
    } catch (error) {
        console.error('Delete error', error);
        res.status(500).json({ message: error.message });
    }
});

module.exports = router;
