export const PAGE_DEFAULTS = {
    home: {
        hero: {
            title: "The Future of Learning <br /> <span class='text-secondary'>Is Immersive</span>",
            subtitle: "Safe360 combines Virtual Reality, AI-driven analytics, and enterprise-grade learning management to transform how your workforce trains, learns, and stays safe.",
            ctaText: "Explore Solutions",
            heroVideo: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?q=80&w=2078&auto=format&fit=crop"
        },
        stats: {
            stat1Label: "Active Learners", stat1Value: "50k+",
            stat2Label: "Modules Completed", stat2Value: "1.2M",
            stat3Label: "Safety Incident Reduction", stat3Value: "40%",
            stat4Label: "Enterprise Clients", stat4Value: "200+"
        }
    },
    about: {
        main: {
            heading: "About <span class='text-secondary'>Safe360</span>",
            intro: "<p>Safe360 is a global leader in immersive safety training technology. Founded in 2020, we have dedicated our mission to reducing workplace accidents through better, more engaging training solutions.</p><p>We believe that when people learn by doing—safely simulated in VR—they retain 75% more information than traditional classroom methods.</p>"
        },
        history: {
            historyText: "<p>Our journey began in a small garage in London, where three engineers obsessed with VR saw a potential to save lives. Fast forward to today, we serve Fortune 500 companies across the globe.</p>"
        }
    },
    services: {
        header: {
            title: "Professional <span class='text-secondary'>Services</span>",
            description: "At Safe360, we offer a comprehensive suite of digital services to empower your business. From cutting-edge software development to strategic digital marketing, our expert team is dedicated to accelerating your growth and ensuring your success in the digital age."
        }
    },
    products: {
        header: {
            title: "Our <span class='text-accent'>Solutions</span>",
            description: "Discover our suite of cutting-edge tools designed to elevate your workforce's safety and performance. Whether you need a robust Learning Management System to track compliance or hyper-realistic Virtual Reality simulations to train for high-risk scenarios, Safe360 has the technology to transform your training operations."
        }
    },
    contact: {
        header: {
            title: "Get in <span class='text-secondary'>Touch</span>",
            description: "Ready to transform your corporate training? Let's start a conversation."
        },
        info: {
            address: "Safe360 HQ, 123 Tech Avenue, London, EC1A 1BB, United Kingdom",
            email: "hello@safe360.com",
            phone: "+44 20 7123 4567"
        }
    },
    privacy: {
        header: {
            title: "Privacy <span class='text-secondary'>Policy</span>",
            description: "We value your privacy and are committed to protecting your personal data."
        },
        content: {
            body: `
<div class="bg-gray-50 dark:bg-white/5 border border-gray-200 dark:border-white/10 rounded-2xl p-8 mb-12 shadow-sm dark:shadow-none transition-colors">
    <p class="text-gray-600 dark:text-gray-300 leading-relaxed">
        Welcome to Safe360. We respect your privacy and want to protect your personal information. This Privacy Policy serves to explain how we collect, use, disclose, and safeguard your information when you visit our website safe360.com and use our training platforms, including our VR/AR applications, mobile apps, and Learning Management System (LMS). Please read this privacy policy carefully. If you do not agree with the terms of this privacy policy, please do not access the site.
    </p>
    <p class="text-gray-600 dark:text-gray-300 leading-relaxed mt-4">
        Safe360 ("us", "we", or "our") operates the website and the Safe360 mobile application (the "Service"). This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
    </p>
</div>

<div class="space-y-16">
    <section>
        <h2 class="text-3xl font-bold text-gray-900 dark:text-white m-0 mb-6">1. Definitions</h2>
        <div class="text-gray-600 dark:text-gray-400 space-y-4 pl-4 border-l-2 border-gray-200 dark:border-white/10">
            <p><strong>Service:</strong> Service is the safe360.com website and the Safe360 mobile application operated by Safe360.</p>
            <p><strong>Personal Data:</strong> Personal Data means data about a living individual who can be identified from those data.</p>
            <p><strong>Usage Data:</strong> Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself.</p>
            <p><strong>Cookies:</strong> Cookies are small pieces of data stored on your device.</p>
        </div>
    </section>

    <section>
        <h2 class="text-3xl font-bold text-gray-900 dark:text-white m-0 mb-6">2. Information Collection and Use</h2>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
            We collect several different types of information for various purposes to provide and improve our Service to you.
        </p>
        
        <h3 class="text-xl font-bold text-gray-900 dark:text-white mt-8 mb-4">Types of Data Collected</h3>
        
        <div class="bg-gray-50 dark:bg-white/5 rounded-xl p-6 mb-6 border border-gray-200 dark:border-white/10 transition-colors">
            <h4 class="text-lg font-bold text-secondary mb-2">Personal Data</h4>
            <p class="text-gray-600 dark:text-gray-400 mb-4">
                While using our Service, we may ask you to provide us with certain personally identifiable information ("Personal Data").
            </p>
            <ul class="list-disc pl-6 text-gray-600 dark:text-gray-400 space-y-1">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Cookies and Usage Data</li>
            </ul>
        </div>
    </section>
    
    <section>
        <h2 class="text-3xl font-bold text-gray-900 dark:text-white m-0 mb-6">Contact Us</h2>
        <p class="text-gray-600 dark:text-gray-400 mb-6">
            If you have any questions about this Privacy Policy, please contact us:
        </p>
        <div class="grid md:grid-cols-2 gap-8 text-gray-600 dark:text-gray-300">
            <div>
                <p class="font-bold text-gray-900 dark:text-white mb-1">By Email:</p>
                <p class="text-secondary">privacy@safe360.com</p>
            </div>
        </div>
    </section>
</div>
`
        }
    }
};
